# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/99_utilities.ipynb.

# %% auto 0
__all__ = ['func_timer']

# %% ../nbs/99_utilities.ipynb 1
from time import time

# %% ../nbs/99_utilities.ipynb 2
def func_timer(func):
    # This function shows the execution time of 
    # the function object passed
    def wrap_func(*args, **kwargs):
        t1 = time()
        result = func(*args, **kwargs)
        t2 = time()
        print(f'Function {func.__name__!r} executed in {(t2-t1):.4f}s')
        return result
    return wrap_func
