# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lake_interface',
                'doc_host': 'https://imcallister.github.io',
                'git_url': 'https://github.com/imcallister/lake_interface',
                'lib_path': 'lake_interface'},
  'syms': {'lake_interface.core': {'lake_interface.core.foo': ('core.html#foo', 'lake_interface/core.py')}}}
