name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: [uses: fastai/workflows/quarto-ghp@master]
