name: CI
on: [pull_request,push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::686411429410:role/github_actions
        role-session-name: lakeinterface-github-actions
    - name: Run tests
      run: |
        nbdev_test
    - name: Deploy github pages
      uses: fastai/workflows/quarto-ghp@master
